export { createIdb } from './idb/index.js';
export { restoreBackup, verifyBackup } from './idb/index.js';
export { inspectStorage } from './idb/index.js';
export type {
  BackupFile,
  BackupOptions,
  BackupResult,
  BackupVerificationResult,
  AutoFieldIndexes,
  AutoIndexAction,
  AutoIndexCandidate,
  AutoIndexDiagnostics,
  AutoIndexPreset,
  CollectionDiagnostics,
  CollectionOperationOptions,
  CollectionStructure,
  CollectionStructureNode,
  CollectionStructureOptions,
  CollectionStructureType,
  CollectionStorageStats,
  DatabaseFileStats,
  ExecuteOptions,
  ExecutionOptions,
  FieldIndexPathRule,
  FieldIndexPatternRule,
  FieldIndexRule,
  FieldIndexes,
  IdbCallback,
  IdbBaseOptions,
  IdbDurability,
  IdbDynamicOptions,
  IdbEngine,
  IdbFilesystemOptions,
  IdbMemoryOptions,
  IdbMode,
  IdbOptions,
  IdbOutcome,
  IdbReadonlyOptions,
  IdbReadwriteOptions,
  IdbDiagnostics,
  MaintenanceResult,
  MutationRow,
  ManagedAutoIndex,
  OptimizeIndexesOptions,
  OptimizeIndexesResult,
  ObservedValueType,
  RestoreBackupOptions,
  RestoreBackupResult,
  StorageStats,
  StorageInspection,
  StreamOptions,
} from './idb/index.js';
